name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    name: "Scan Ruby"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      # --- 権限付与ステップを追加 ---
      - name: Set execute permissions for scripts
        run: chmod +x bin/*
      - name: Scan for common Rails security vulnerabilities
        run: bin/brakeman --no-pager

  scan_js:
    name: "Scan JavaScript"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      # --- 権限付与ステップを追加 ---
      - name: Set execute permissions for scripts
        run: chmod +x bin/*
      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      # --- 権限付与ステップを追加 ---
      - name: Set execute permissions for scripts
        run: chmod +x bin/*
      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    name: "Test"
    runs-on: ubuntu-latest
    # --- PostGISサービスを定義 ---
    services:
      postgres:
        image: postgis/postgis:13-3.1 # postgisイメージに変更
        env:
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
          POSTGRES_DB: wanderpath_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      # --- 権限付与ステップを追加 ---
      - name: Set execute permissions for scripts
        run: chmod +x bin/*
      - name: Run tests
        env:
          RAILS_ENV: test
          # --- サービスコンテナの情報を環境変数として渡す ---
          DATABASE_HOST: localhost
          DATABASE_USER: rails
          DATABASE_PASSWORD: password
          DATABASE_NAME: wanderpath_test
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rails test
